### ISSUE TITLE
Plan

### ISSUE THREAD

**Issue by mrocklin** [pydata/parallel#1]
@minrk @quasiben 

So we now have this new repository for Python Parallel documentation and a SciPy tutorial.  How do we want to lay it out?  How do we want to draft and organize content?

**Comment by minrk** [comment]
With my Jupyter hat on, I like putting together notebooks, perhaps with a few directories for broad topics, depending on how much content we have. For our outline, we have:

## Part one
1. Parallel Map
2. Asynchronous Futures
3. High Level Datasets
4. Streaming

## Part two
1. Processes and Threads.  The GIL, inter-worker communication, and contention
2. Latency and overhead.  Batching, profiling.
3. Communication mechanisms.  Sockets, MPI, Disk, IPC.
4. Stuff that gets in the way.  Serialization, Native v. JVM, Setup, Resource Managers, Sample Configurations
5. Debugging async and parallel code / Historical perspective

So perhaps a part 1 and part 2 directory.

**Comment by quasiben** [comment]
Starting with notebook/examples seems like a good plan

**Comment by mrocklin** [comment]
Do we have good example datasets that we can reliably deliver to users?  When building a dask tutorial for PyData Seattle 2015 I made [some scripts](https://github.com/dask/dask-tutorial/blob/master/prep.py) to auto-generate some data.  Can anyone recommend similar dataset generators that might produce data of a decent size?  

Alternatively we could host data online and have them act online.

**Comment by Asma-Saad** [comment]
what about covid-19 dataset

**Comment by quasiben** [comment]
@Asma-Saad thanks for the interest but this repository is large unused.  We have since developed several examples and a tutorial here:
- https://examples.dask.org/
- https://tutorial.dask.org/
